[package]
name = "FinalProject"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
clap = { version = "4.3", features = ["derive"] }
num_cpus = "1.16"
chrono = "0.4"
